# This is the docker-compose.yml I use with Traefik v2, feel free to use it.
version: '3'

networks:
  http_network:
    external: true
  mastodon_network:
    external: false

services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    labels:
      # There you should configure as you like: https://docs.traefik.io/user-guides/docker-compose/basic-example/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /home/docker/traefik/acme.json:/acme.json
      - /home/docker/traefik/config.yml:/config.yml
    networks:
      - http_network

  mastodon-db:
    image: postgres:9.6-alpine
    container_name: mastodon-db
    restart: unless-stopped
    volumes:
      - /home/docker/mastodon/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mastodon
      - POSTGRES_DB=mastodon
      - POSTGRES_PASSWORD=
    networks:
      - mastodon_network

  mastodon-redis:
    image: redis:6.0-alpine
    container_name: mastodon-redis
    restart: unless-stopped
    volumes:
      - /home/docker/mastodon/redis:/data
    networks:
      - mastodon_network

  mastodon:
    image: mastodon
    container_name: mastodon
    restart: unless-stopped
    env_file: /home/docker/mastodon/.env.production
    networks:
      - http_network
      - mastodon_network
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - /home/docker/mastodon/data:/mastodon/public/system
      - /home/docker/mastodon/logs:/mastodon/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.mastodon-web.entrypoints=http
      - traefik.http.routers.mastodon-web.rule=Host(`domain.tld`)
      - traefik.http.routers.mastodon-web.middlewares=https-redirect@file
      - traefik.http.routers.mastodon-web-secure.entrypoints=https
      - traefik.http.routers.mastodon-web-secure.rule=Host(`domain.tld`)
      - traefik.http.routers.mastodon-web-secure.tls=true
      - traefik.http.routers.mastodon-web-secure.tls.certresolver=http
      - traefik.http.routers.mastodon-web-secure.service=mastodon-web
      - traefik.http.services.mastodon-web.loadbalancer.server.port=3000
      - traefik.http.routers.mastodon-streaming.entrypoints=http
      - traefik.http.routers.mastodon-streaming.rule=Host(`domain.tld`) && PathPrefix(`/api/v1/streaming`)
      - traefik.http.routers.mastodon-streaming.middlewares=https-redirect@file
      - traefik.http.routers.mastodon-streaming-secure.entrypoints=https
      - traefik.http.routers.mastodon-streaming-secure.rule=Host(`domain.tld`) && PathPrefix(`/api/v1/streaming`)
      - traefik.http.routers.mastodon-streaming-secure.tls=true
      - traefik.http.routers.mastodon-streaming-secure.tls.certresolver=http
      - traefik.http.routers.mastodon-streaming-secure.service=mastodon-streaming
      - traefik.http.services.mastodon-streaming.loadbalancer.server.port=4000
      - traefik.docker.network=http_network
